on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format files
        run: |
          sudo apt install emacs 
          bash ./lisp-format src/generator.lisp > generator_form.lisp
          bash ./lisp-format src/input.lisp > input_form.lisp
          bash ./lisp-format src/main.lisp > main_form.lisp
          bash ./lisp-format src/methods.lisp > methods_form.lisp
          bash ./lisp-format src/run.lisp > run_form.lisp
          bash ./lisp-format src/utils.lisp > util_form.lisp
      - name: Compare with format
        run: |
          diff src/generator.lisp generator_form.lisp
          diff src/input.lisp input_form.lisp
          diff src/main.lisp main_form.lisp
          diff src/methods.lisp methods_form.lisp
          diff src/run.lisp run_form.lisp
          diff src/utils.lisp util_form.lisp
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup SBCL
        uses: cheeze2000/setup-sbcl@v1
        with:
          version: 2.2.8
      - name: Verify installation
        run: sbcl --non-interactive --eval "(print (ql:client-version))" --eval "(print (asdf:asdf-version))"
      - name: Test
        run: sbcl --script test/test.lisp
